//
//  StyleKit.swift
//  ProgressBar-Test
//
//  Created by AuthorName on 21/08/2017.
//  Copyright (c) 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Drawing MethodsCGRect(x: 0, y:0, width: 300, heigth: 16), progress: CGFloat = 189)
    public class func drawProgressBar(frame: CGRect = CGRect(frame, frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 16)), progress: CGFloat = 183) {
        //// Color Declarations
        let color = UIColor(red: 0.697, green: 0.094, blue: 0.094, alpha: 1.000)

        //// Progress Border Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(frame.minX + 1, frame.minY + 1, floor((frame.width - 1) * 0.99666 + 0.5), 14), cornerRadius: 7)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// Progress Active Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRectMake(1, 1, progress, 14), cornerRadius: 7)
        color.setFill()
        progressActivePath.fill()
    }
}
